# Configuration Railway pour SmartStock
# Railway utilise Nixpacks pour d√©tecter et builder automatiquement Laravel

[build]
builder = "NIXPACKS"
buildCommand = "npm run build"

[deploy]
startCommand = "bash heroku-start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Health check
healthcheckPath = "/login"
healthcheckTimeout = 300
